name: ci-build
on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    strategy:
      matrix:
        os: [2019, 2022]
    runs-on: windows-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        shell: bash
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          export IMAGE_TAG=$(echo "${GITHUB_HEAD_REF}" | sed "s/\//-/g")-${{ matrix.os }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t windows-event-gen:${IMAGE_TAG} --build-arg SERVER_VERSION=${{ matrix.os }} .
